#!/bin/bash


case $1 in

# install a program
  -i)
     touch pkg-files
     axel -a --output=$2-pkg https://raw.githubusercontent.com/hexisXz/hexpmg/main/pkg-files/$2-pkg && source ~/"$2-pkg" && echo "$2" >> pkg-files

    ;;

# remove a program
  -R)
    # if you also want to remove the folder that belongs to the program
    # put && sudo rm -r $2 after sudo rm /bin/$2
    sudo rm /bin/$2 && sudo rm -r $2

    e=$(ls | grep -i $2-pkg)

    if command -v $e >/dev/null; then
	    exit 1
    else
       rm $2-pkg
    fi


    ;;

# remove all -pkg files
  -RAP)
      rm *-pkg
      ;;

# list all installed programs 
  -l)
    cat pkg-files
    ;;

# display a list of all commands
  -h)
    echo "usage: [-i install a program

        -R remove a program
		
        -l list all installed programs
		  
        -RAP Remove All -pkg files]"
    ;;

  *)
   echo "error: wrong command"
   ;;
esac
