#!/bin/bash

# colors
red='\033[0;31m'
blue='\033[0;34m'
green='\033[0;32m'
purple='\033[0;35m'
NC='\033[0m' # No Color



case $1 in

# install a program
  -i)
    echo -e "${blue}creating list file"
     touch pkg-files
     echo -e "${green}Downloading"
     axel -a --output=$2-pkg https://raw.githubusercontent.com/hexisXz/hexpmg/main/pkg-files/$2-pkg && source ~/"$2-pkg" && echo "$2" >> pkg-files

    ;;

# remove a program
  -R)
    # if you also want to remove the folder that belongs to the program
    # put && sudo rm -r $2 after sudo rm /bin/$2
    echo -e "${red}removing program"
    sudo rm /bin/$2 && sudo rm -r $2

    e=$(ls | grep -i $2-pkg)

    if command -v $e >/dev/null; then
	    echo -e "${green}Done"
 	    exit 1
    else
       echo -e "${red}removing pkg file"
       rm $2-pkg
       echo -e "${green}Done"
    fi


    ;;

# remove all -pkg files
  -RAP)
      rm *-pkg
      ;;

# list all installed programs 
  -l)
    cat pkg-files
    ;;

# display a list of all commands
  -h)
    echo "usage: [-i install a program

        -R remove a program
		
        -l list all installed programs
		  
        -RAP Remove All -pkg files]"
    ;;

  *)
   echo -e "${red}error: wrong command"
   ;;
esac
