#!/bin/bash


case $1 in

  -i)
    source ~/hexpmg/pkg-files/"$2-pkg"
    ;;

  -R)
    sudo rm /bin/$2
    ;;

  -h)
    echo "usage: [ install [install a program] ]"
    ;;

  *)
   echo "error: wrong command"
   ;;
esac




