#!/bin/bash

##########
# V 1.90.1#
##########



# colors
red='\033[0;31m'
blue='\033[0;34m'
green='\033[0;32m'
purple='\033[0;35m'
NC='\033[0m' # No Color



case $1 in

# install a program
  -i)
     echo -e "${green}Downloading${purple}"
     sh <(curl -L https://raw.githubusercontent.com/hexisXz/scoria-repo/main/$2/$2-pkg) && echo -e "${green}Done"

    ;;



  -ib)
      echo -e "${green}Downloading${purple}"
      sh <(curl -L https://raw.githubusercontent.com/hexisXz/scoria-repo/main/$2/$2-pkg.b) && echo -e "${green}Done"

    ;;



# list all installed programs
  -l)
     ls -al /usr/local/src/

   ;;


# uninstall scoria
  -UN)
     exec ~/.config/hexpmg/uninstall/uninstall
     ;;

# update scoria
  -UP)
     exec ~/.config/hexpmg/update/update
     ;;

# remove a program
  -R)
     echo -e "${red}removing program"
     cd /usr/local/src/$2 ; sh <(curl -v -L https://raw.githubusercontent.com/hexisXz/scoria-repo/main/$2/uninstall)    

     echo -e "${green}Done"

    ;;

# update a program
   -U)
      echo -e "${purple}updating program${blue}"
      cd /usr/local/src/$2 && sh <(curl -v -L https://raw.githubusercontent.com/hexisXz/scoria-repo/main/$2/uninstall) 

      sh <(curl -v -L https://raw.githubusercontent.com/hexisXz/scoria-repo/main/$2/$2-pkg) 2> /dev/null

      case $? in
           1)
            echo -e "${red}Error wrong URL" && exit 1

           ;;
      esac

      echo -e "${green}Done"

      ;;



# search for a package
  -s)
    curl -L https://raw.githubusercontent.com/hexisXz/scoria-repo/main/$2/$2-pkg | grep -i pkgname && echo "package found." || echo "ERROR: no packages found."
      ;;



# display a list of all commands
  -h)
    echo -e "${blue}usage: [-i install a program

       -ib: install a binary program
 
       -s: search for a package

        -R: remove a program

	-l: list all installed programs

	-U: update a program
	
	-UP: update scoria
	
	-UN: uninstall scoria]
"
   ;;
  *)
   echo -e "${blue}usage: [-i: install a program

        -ib: install a binary program
   
        -s: search for a package

        -R: remove a program

        -l: list all installed programs

	-U: update a program
	
	-UP: update scoria
	
	-UN: uninstall scoria]"

   ;;
esac
