#!/bin/bash

pkgname='dmenu'

pkgdescription="a dynamic menu for X, originally designed for dwm. It manages large numbers of user-defined menu items efficiently."

pkgsource="https://dl.suckless.org/tools/dmenu-5.2.tar.gz"

dependencies="axel"

pkginstall='zip'


pkgconfig() {
	if [ "$pkginstall" == "zip" ]; then
		sudo apt install axel && axel -a https://dl.suckless.org/tools/dmenu-5.2.tar.gz && gunzip dmenu-5.2.tar.gz && tar --extract -f dmenu-5.2.tar && cd dmenu && sudo make install
	fi
}


	

pkgconfig
