#!/bin/bash

pkgname='neofetch'

pkgdescription='A command-line system information tool written in bash 3.2+ '

pkgsource='https://github.com/dylanaraps/neofetch.git'

dependencies="make"

pkginstall='make'


pkgconfig() {
	if $dependencies -v cmatrix >/dev/null; then
		git clone $pkgsource && cd $pkgname && sudo make instal
	else
           sudo apt install make && git clone $pkgsource && cd $pkgname && sudo make install
        fi
}


pkgconfig
