#!/bin/bash

# colors
red='\033[0;31m'
blue='\033[0;34m'
green='\033[0;32m'
purple='\033[0;35m'
NC='\033[0m' # No Color


echo -e "${green}updating"

sudo rm -r ~/.local/bin/hexpmg && sudo rm -r ~/.config/hexpmg && echo -e "${blue}hexpmg will now reinstall.${green}" && sh <(curl -v -L https://raw.githubusercontent.com/hexisXz/hexpmg/main/install.sh)

