#!/bin/bash

# colors
red='\033[0;31m'
blue='\033[0;34m'
green='\033[0;32m'
purple='\033[0;35m'
NC='\033[0m' # No Color


echo -e "${green}updating"

if command -v yay 2>/dev/null; then
		yay -Syu

else
   sudo rm /bin/hexpmg && sudo rm -r ~/.config/hexpmg && sudo rm -r hexpmg && echo -e "${blue}hexpmg will now reinstall.${green}" && git clone https://github.com/hexisXz/hexpmg.git && cd hexpmg && ./install.sh && sudo rm -r ~/hexpmg

fi
